### ISSUE TITLE
How do I enable .fromNow() formatting?

### ISSUE THREAD

**Issue by Industrial** [wyuenho/backgrid-moment-cell#11]
I would like to format some dates, non editable like "3 hours ago".

**Comment by afflicto** [comment]
I'd like to do that too!

**Comment by rockerest** [comment]
Hi all, I know this is coming at you very late but I figured I'd add a thought.

Essentially this request means outputting a string into a cell. The power of a MomentCell is in it's underlying Moment object. True, if you output "3 hours ago" it can still have the Moment object underneath, but you're essentially using it as a string field.

To that end I suggest the alternative of calculating a "display[MyDate]" string in the code, and then assigning that to the Backgrid column.

For what it's worth, I do this with [EpoxyJS](http://epoxyjs.org/documentation.html#model-computeds). The model may not be the right place for the computed, but you can play with [other locations](http://epoxyjs.org/documentation.html#view-computeds). In essence: the true date is left unchanged, a computed value is created (somewhere) that feeds from the true date (when the true date changes, so does the computed value). The computed value is then used in the table as a string.

So:

`Date => HumanFriendlyDate`

then in the Backgrid definition:

    columns: [ {
        'name': 'HumanFriendlyDate',
        'cell': 'string'
    } ];

Obviously this doesn't add support for this feature explicitly in the cell definition, but it has the benefit of globalizing this feature across your application: if you want to display that same format in something other than Backgrid, you can use the same calculated property.

I'm not affiliated with Backgrid or Jimmy Yuen Ho Wong. Just hoping to help a little bit.

**Comment by wyuenho** [comment]
The problem with `fromNow` is you cannot not parse the humanized timestamp strings back to a Date object, and subsequently a datetime string. If you just need a cell to display a humanized datetime string, it's trivial to do it yourself by just providing a customer formatter similar to @rockerest said.
